---
title: "R Style Guide"
author: "Nicholas Viau"
date: "November 13, 2017"
output:
  html_document:
    css: styles.css
    toc: no
    toc:depth: 5
    self_contained: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Code readability is an important step in project management. If code is written poorly not only is it difficult to read, but it will be frustrating to extend and potentially onerous to debug. There is no official R style manual, nor is there necessarily a "right" or "wrong" way to write code. However, there are many conventions that almost universally accepted, and many others that just make sense. That being said, this guide is based on several R style guides found on the web. Most notably: 

* Hadley Wickham's [R Style Guide](http://adv-r.had.co.nz/Style.html) and the [tidyverse style guide](http://style.tidyverse.org/).
* Google's [R style guide](https://google.github.io/styleguide/Rguide.xml).
* Jennifer Bryan's [personal website](https://www.stat.ubc.ca/~jenny/STAT545A/block19_codeFormattingOrganization.html).
* Jean Fan's [guide](http://jef.works/R-style-guide/)
* Paul Johnson's [vignette](https://cran.r-project.org/web/packages/rockchalk/vignettes/Rstyle.pdf).

This guide is not orthodoxy. If anything, the most important thing is that you should use consistent style. 

***

## Notation and Naming

### File Names

Files can proliferate very quickly in even a modest project. To keep things under control, file names should make sense, but be conservative about long they are. Always try to avoid adding ad  hoc numbers at the end of files that perhaps made sense at the time of writing them, but not at all in the present. Also, file names whould always end in `.R`

**Good:**

```
fit-models.R
utility-functions.R
```

**Bad:**

```
stuff3.r
ok.R
```

If files need to be run in sequence, prefix them with numbers:

```
0-download.R
1-parse.R
2-explore.R
```

If you think you'll have more than 10 files, left pad them with zeroes: 

```
00-download.R
01-parse.R
...
12-plot.R
13-publish.R
```

If you are creating a testing file, create a separate file with the suffix "`_test`" attached. For example, `originalfilename_test.R`. 

Also pay attention to capitalization. While many operating systems tend to be case-insensitive, R and many version control systems are case sensitive. Generally, I prefer files names that all lower case.

I also suggest utilizing symbol chracters for breaks in file names. Most programs don't work well with spaces in the file paths. The added benefit of this is that if you use specialty symbols such as "_" to break different parts, you can split file names using regular expressions when running scripts across multiple files of the same set. [*Source*](https://www.stat.ubc.ca/~jenny/STAT545A/block19_codeFormattingOrganization.html#naming-things)

### Object Names

Variable and function names should be lowercase. Use underscores (_) to separate words within a name. Generally, variable names should be nouns and function names should be verbs. Always strive for names that are both succinct and meaningful, thought this is not always easy.

Avoid using names of existing / common functions or variables. For instance, don't name things "x" or create a function called "mean".

***

## Syntax

### General

For assigment, always use `<-` not `=`.

Do not use `;` to carry out multiple commands on a single line. It makes things very confusing.

### Spacing

Keep spaces between all infix operators (`=`, `+`, `<-`, etc.), and when naming arguments in function calls. Commas should follow regular English rules -- i.e., always a put a space after, but never before.

**Good:**

```
average <- mean(feet / 12 + inches, na.rm = TRUE)
```

**Bad:**

```
average<-mean(feet/12+inches,na.rm=TRUE)
```

### Long Lines

Always strive to keep your code to 80 characters per line. RStudio will include a grey line in the script as a guide. If you find yourself using up space quickly, it may be the case that you encapsulate some of the work in a separate function. [Source](http://style.tidyverse.org/syntax.html#long-lines)

***

## Piping Operations

*For more on this see my notes on piped operations and the tidyverse.*

Use the pipe operator `%>%` when you need to compile three or more functions together in a nested call, or when you are creating intermediate objects that you do not need. Each verb should have its own line. Following these rules will make it simpler to understand, rearrange, and debug.

> **Note:** The `%>%` operation comes from the magrittr package. Most tidyverse packages automatically load it, but sometime you may need to load magrittr explicitly. I often always include it at the start of my scripts for this reason.

While pipes play a fundamental role in code, you should avoid using the pipe operator when:

* You need to manipulate more then one object at a time. A pipe should only be for a sequence of actions applied to one primary object.
* There are meaningful intermediate objects that could be given informative names.

### Spacing and Indenting

`%>%` should have a space before it and a new line after it. After each step, each line should be indeneted two spaces (Rstudio will automatically indent piped operations).

Though there's nothing wrong with have a one-step pipe, you may want to rewrite to remove the pipe depending on the context.

```
# This works
iris %>% arrange(Petal.Width)

# So does this
arrange(iris, Petal.Width)
```

These commands both do the same thing.

### Long Lines

Bear in mind our ~80 chracter line limit. If you find yourself writing a piped function with very long lines, put each subargument on its own line.

This:

```
iris %>%
  group_by(Species) %>%
  summarise(
    Sepal.Length = mean(Sepal.Length),
    Sepal.Width = mean(Sepal.Width),
    Species = n_distinct(Species)
  )
```

Is much better than this:

```
iris %>%
  group_by(Species) %>%
  summarise(
    Sepal.Length = mean(Sepal.Length), Sepal.Width = mean(Sepal.Width), Species = n_distinct(Species)
  )
```

### Assignment

When working with pipes you should keep with the assignment conventions above. That being said, you can assign a new object with `->` at the end of the pipe. Avoid this technique. Beginning the code with the assignment ensure the name of the object serves as a heading, which reminds you the purpose of the pipe.

You can also use the `%<>%` in magrittr. For example,

```
mtcars <- mtcars %>% 
  transform(cyl = cyl * 2)
```

is equivalent to

```
mtcars %<>% transform(cyl = cyl * 2)
```

However, you should stick with `<-` for any assignment operation. It should be clear whats happening to the data. A little bit of duplication (repeating the name of the object twice) is worth the clarity of the assignment.

### Commenting 

In-line comments work fine within pipes. However, though they are very helpful at the early stages of analysis, keep comments to a minimum. As explained earlier, if you find yourself writing more comments than code, perhaps switch to RMarkdown.

***

## Dealing With Duplication

Always strive to reduce code duplication. This will have three main benefits:

1. It illuminates the intent of your code, because your eyes are drawn to what's different, not what stays the same.
2. It's much easier to make changes. You may need to change code not because of error, but because your needs change. Rather than remembering every location you copied-and-pasted code, you only need to make changes in one place.
3. You'll ultimately have fewer bugs.

### Functions

Functions reduce duplication by identifying repeated patterns of code.

### Iteration

Another helpful tool for reducing duplication is **iteration**, which is handy when you need to do the same thing to multiple inputs. The [purrr](http://purrr.tidyverse.org/) package is a core tidyverse package and it provides a bevy of powerful programming tools.

***

## Other Miscellaneous Topics

### Replicating Randomness

Always use the `set.seed()` function in order to guarantee randomly generated data occurs as it did in initital analysis.



